# Please specify your endpoints, and the expected content
#
#eg.
#    - url: "http://www.google.com"
#      content: ""

refresh_rate: 10
sites:
    - url: https://www.publico.pt
      content: CLASSIFICADOS
    - url: https://www.publico.pt
      content: ZONA
    - url: http://www.fsecure.com
      content: Suojaa kaikki laitteesi</h1>
    - url: https://www.facebook.com
      content: Friends
    - url: http://this.is.a.bad.bad.site/
      content: none
    - url: https://github.com/wrong_page
      content: This is not the web page
    - url: https://aws.amazon.com
      content: Amazon
