# Please specify your endpoints, and the expected content
# 

refresh_rate: 10
Sites:
#eg.
#    - url: "http://www.google.com"
#      content: ""
#    - url: https://www.f-secure.com
#      content: Security
#    - url: https://www.facebook.com
#      content: connect with friends 
    - url: https://www.publico.pt
      content: CLASSIFICADOS         
    - url: https://www.publico.pt
      content: ZONA  
    - url: http://www.fsecure.com
      content: Suojaa kaikki laitteesi</h1>
