# This file configures the urls to check
# the content (case-insensitive) to find at each url
# and the refresh rate of the checks
#
# e.g.
# sites:
#    - url: http://www.google.com
#      content: I'm feeling lucky
#
# default rate for checks, can be overriden by cmd-line
refresh_rate: 10
sites:
    - url: https://www.publico.pt
      content: CLASSIFICADOS
    - url: https://www.publico.pt
      content: ZONA
    - url: http://www.fsecure.com
      content: Suojaa kaikki laitteesi</h1>
    - url: https://www.facebook.com
      content: modesty
    - url: http://this.is.a.bad.bad.site.com/
      content: none
    - url: https://github.com/wrong_page
      content: This is not the web page
    - url: https://aws.amazon.com
      content: Amazon
    - url: http://localhost:8080/500
      content: error
    - url: http://localhost:80/500
      content: error
    - url: http://www.google.com/
      content: search
    - url: http://www.esa.int
      content: Space for Europe
    - url: http://www.python.org
      content: Python is a programming language
    - url: https://www.linkedin.com
      content: Find a colleague
    - url: http://www.reddit.com
      content: subscribe to our newsletter
